# Generated by Django 4.2.21 on 2025-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="None", max_length=256),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
